### PR TITLE
Documenting how to use enzyme with react 16. Fixes #131.

### LINKED ISSUE #131: Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
Following the documentation of this tutorial the **Hello.test.tsx** files errors like the title above.

From what I read online, the packages `@types/enzyme` and `react-addons-test-utils` would suffice the need to configure an adapter manually on a testsSetup.js

That didn't work.

I took the second route and wrote a **testsSetup.js** inside my `src `

**setupTests.js** (should this be `.ts` , `.tsx`?, either way it did not work)
```javascript
import * as enzyme from 'enzyme';
import * as Adapter from 'enzyme-adapter-react-16';

enzyme.configure({ adapter: new Adapter() });
```

**Hello.test.tsx**

```javascript
import * as React from 'react';
import * as enzyme from 'enzyme';
import Hello from './Hello';

it('renders the correct text when no enthusiasm level is given', () => {
    const hello = enzyme.shallow(<Hello name='Daniel' />);
    expect(hello.find(".greeting").text()).toEqual('Hello Daniel!')
});
```
**Package.json**

```javascript 
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-scripts-ts": "2.14.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/enzyme": "^3.1.9",
    "@types/enzyme-adapter-react-16": "^1.0.2",
    "@types/jest": "^22.2.2",
    "@types/node": "^7.0.60",
    "@types/react": "^16.3.6",
    "@types/react-dom": "^16.0.4",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "react-addons-test-utils": "^15.6.2",
    "typescript": "^2.8.1"
  }
}
```

Another source suggested adding extra config to jest on package.json such as 

```javascript
........
  "jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupTests.js"
  }
```

However that errors as:
```javascript
These options in your package.json Jest configuration are not currently supported by Create React App:

  • setupTestFrameworkScriptFile

```

**Further...**
A fresh clone of this repo errors out not running any test suites and complaining about cheerio names.

How can we get the **Enzyme Adapter** to work with the current project setup on `.tsx` files?

### PR DESCRIPTION
**Pull request by catchin**
As there has been some confusion how to include enzyme in https://github.com/Microsoft/TypeScript-React-Starter/issues/131 , I updated the README at this place. Let me know if something needs to be changed.

### CODE REVIEW

**Comment by ShawnXiao105** [comment]
@catchin I follow your pr to add `react-test-renderer` and `enzyme-adapter-react-16` without use eject. `npm test` still fail.

The error message is the same as 

    These options in your package.json Jest configuration are not currently supported by Create React App:

      • setupTestFrameworkScriptFile

**Comment by catchin** [comment]
@ShawnXiao105 Can you share what steps you performed? I just created an app from scratch and it works. In this repo you see what steps I performed (as single commits) and what the code looks like: https://github.com/catchin/react-typescript-example-with-enzyme

Did you modify package.json to include a ``setupTestFrameworkScriptFile`` configuration? Because this is not necessary. Also, which version of ``react-scripts-ts`` do you use?

**Comment by ShawnXiao105** [comment]
@catchin  It works now. The reason is that I add JTEST options in package.json. And I removed them and all thing is OK.

**Comment by DanielRosenwasser** [comment]
Thank you so much for the PR and thanks for your patience!

**Comment by catchin** [comment]
Thanks for merging!

**Pull request merged**
